---

- name: Install packages Debian
  apt:
    name: "{{item}}"
    state: present
  when: ansible_os_family == 'Debian'
  with_items:
    - git

- name: Install packages CentOS
  yum:
    name: "{{item}}"
    state: present
  when: ansible_os_family == 'RedHat'
  with_items:
    - git

- name: Clone project
  git:
    repo: "{{ ah_git_url }}"
    dest: "/opt/{{ ah_name }}"
    force: yes
    version: "{{ ah_version }}"
  notify:
   - Restart service

- name: Link directories
  file:
    src: "/opt/{{ ah_name }}/etc/{{ ah_name }}"
    dest: "/etc/{{ ah_name }}"
    state: link

- name: Install python
  include_role:
    name: pyslackers.python
  vars:
    virtualenvs:
      "{{ ah_name }}":
        path: "/opt/{{ ah_name }}/.env"
        version: "{{ ah_python_version }}"
        requirements: "/opt/{{ ah_name }}/{{ ah_requirements_path }}"

- name: Create systemd directories
  file:
    path: /etc/systemd/system
    state: directory

- name: Configure systemd socket
  template:
    src: "{{ ah_systemd_socket_template | default('etc/systemd/system/project.socket.j2') }}"
    dest: "/etc/systemd/system/{{ ah_name }}.socket"
    force: yes
  register: ah_socket_config
  notify:
    - Restart socket

- name: Configure systemd service
  template:
    src: "{{ ah_systemd_service_template | default('etc/systemd/system/project.service.j2') }}"
    dest: "/etc/systemd/system/{{ ah_name }}.service"
    force: yes
  register: ah_service_config
  notify:
    - Restart service

- name: Systemd daemon-reload
  tags:
    - travis-exempt
  systemd:
    daemon-reload: yes
  when:
    - "ah_service_config.changed or ah_socket_config.changed"

- name: "Enable {{ ah_enabled }} systemd socket"
  tags:
    - travis-exempt
  systemd:
    name: "{{ ah_name }}.socket"
    enabled: "{{ ah_enabled }}"
    masked: False

- name: "Enable {{ ah_enabled }} systemd service"
  tags:
    - travis-exempt
  systemd:
    name: "{{ ah_name }}.service"
    enabled: "{{ ah_enabled }}"
    masked: False

- name: Start systemd socket
  tags:
    - travis-exempt
  systemd:
    name: "{{ ah_name }}.socket"
    masked: False
    state: started
  when:
    - ah_enabled

- name: Start systemd service
  tags:
    - travis-exempt
  systemd:
    name: "{{ ah_name }}.service"
    masked: False
    state: started
  when:
    - ah_enabled
