---

- name: Restart socket
  systemd:
    name: "{{ ah_name }}.socket"
    daemon-reload: True
    state: restarted
  when: "'travis' not in group_names"

- name: Restart service
  systemd:
    name: "{{ ah_name }}.service"
    daemon-reload: True
    state: restarted
  when: "'travis' not in group_names"
