---

- name: Restart socket
  systemd:
    name: "{{ ah_name }}.socket"
    state: restarted
  when:
    - "'travis' not in group_names"
    - "ah_enabled"

- name: Restart service
  systemd:
    name: "{{ ah_name }}.service"
    state: restarted
  when:
    - "'travis' not in group_names"
    - "ah_enabled"
